<a href="https://colab.research.google.com/github/4nnisa/data-excel-colab/blob/main/Numpy_%26_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [ ]:
# Membuat dan Mengakses Array Python
import numpy as np

# membuat array
nilai = np.array([85, 55, 40, 90])
# mengakses data pada array
print(nilai [3])

90

In [ ]:
# Ndarray shape (Membuat Array Dua Dimensi dengan NumPy)

a=np.array([[1,2,3,4],[5,6,7,8])

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (3934586025.py, line 3)

In [ ]:
# Perbaikan (Membuat Array Dua Dimensi dengan NumPy)

a = np.array([[1, 2, 3, 4],
              [5, 66, 7, 8]])

print(a)

[[ 1  2  3  4]
 [ 5 66  7  8]]

In [ ]:
#T2.4 (Mengubah Bentuk Array dengan NumPy)
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#T2.4 ketika di ubah ke 3*3 (Mengubah Bentuk Array NumPy)
a = np.array([[1,2,3],
              [4,5,6]])

b = a.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [ ]:
# Perbaikan T2.4 (Mengubah Bentuk Array NumPy)

a = np.array([[1,2,3],
              [4,5,6]])

b = a.reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# T2.5

a = np.arange(24)
b = a.reshape(2, 3, 4) # Changed to (2,3,4) so that 2*3*4 = 24, matching the array size.
b

In [ ]:
# Perbaikan T2.5

a = np.arange(24)
b = a.reshape(2, 3, 4)
b

In [ ]:
# T3.3

np.arange(2,6,5)

array([2])

In [ ]:
# T3.4

a = np.arange(3, 10, 3)
a

array([3, 6, 9])

In [ ]:
# T4.2

urutan = np.linspace(0, 10, 4, dtype=int)
print("Urutan:", urutan)

Urutan: [ 0  3  6 10]

In [ ]:
# T9 Pembagian antar elemen matriks


A = np.array([[2, 4], [10, 12]])
B = np.array([[1, 2], [5, 6]])
C = A / B
print(C)

[[2. 2.]
 [2. 2.]]

In [ ]:
# T10.19

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
hasil = np.append(arr1, arr2)
hasil

array([1, 2, 3, 4, 5, 6])

In [ ]:
# T10.20

# Membuat array NumPy
arr1 = np.array([1, 2, 3, 4, 5])

# Menyisipkan beberapa nilai sekaligus pada indeks ke-2
arr1_baru = np.insert(arr1, 2, [9, 9, 9])

print("Arr1 asli:", arr1)
print("Arr1 baru:", arr1_baru)

Arr1 asli: [1 2 3 4 5]
Arr1 baru: [1 2 9 9 9 3 4 5]

# **PANDAS**

In [ ]:
import numpy as np
import pandas as pd

# P1

ds = pd.Series([2, 4, 6, 8, 10])
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [ ]:
# P2

import pandas as pd

# Contoh DataFrame
data = {
    "Produk": ["Laptop", "HP", "Printer", "Tablet", "Kamera"],
    "Kategori": ["A", "B", "C", "D", "E"],
    "Harga": [10, 5, 3, 7, 8]
}

df = pd.DataFrame(data)
print(df)

    Produk Kategori  Harga
0   Laptop        A     10
1       HP        B      5
2  Printer        C      3
3   Tablet        D      7
4   Kamera        E      8

In [ ]:
# P3

df_A = df[df["Kategori"] == "A"]
print(df_A)

   Produk Kategori  Harga
0  Laptop        A     10

In [ ]:
# P4

datal = pd.read_csv(
    "https://raw.githubusercontent.com/Alam-A99/Pandas_Latih/10ebb3af000e930a44989075733f495d5c2f4be5/penjualan.csv"
)

datal

      nama  jan  feb  mar  apr
0     Andi  100  135   85   75
1     Budi  200  240  185  160
2  Chandra  300  315  285  190
3     Dudi  250  270  230  200
4      Eko  150  195  110  100
5    Fahri   95  130   75   45
6     Gina  125  175  110   70
7   Herman  130  155  100   85
8   Indara  320  374  300  270
9     Joni  200  220  175  155

In [ ]:
datal['feb'].mean()

np.float64(220.9)

In [ ]:
# P4

data1 = pd.read_csv("https://raw.githubusercontent.com/Alam-A99/Pandas_Latih/10ebb3af000e930a44989075733f495d5c2f4be5/penjualan.csv")
datal
#data1.head()
#data1.describe()
#data1.info()
#data1.tail()
#data1.shape
#data1.columns
#data1.dtypes

      nama  jan  feb  mar  apr
0     Andi  100  135   85   75
1     Budi  200  240  185  160
2  Chandra  300  315  285  190
3     Dudi  250  270  230  200
4      Eko  150  195  110  100
5    Fahri   95  130   75   45
6     Gina  125  175  110   70
7   Herman  130  155  100   85
8   Indara  320  374  300  270
9     Joni  200  220  175  155

In [ ]:
# Data bukan jan yang >100, bulan feb <300

data1.loc[(data1["jan"] > 100) & (data1["feb"] < 300), ["nama", "jan", "feb"]]

     nama  jan  feb
1    Budi  200  240
3    Dudi  250  270
4     Eko  150  195
6    Gina  125  175
7  Herman  130  155
9    Joni  200  220

In [ ]:
#rata rata bulan januari
rata2_jan = data1["jan"].mean()
print("Rata-rata bulan Januari =", rata2_jan)

#variansi bulan januari
variansi_jan = data1["jan"].var()
print("Variansi bulan Januari =", variansi_jan)

#standar deviasi bulan januari
std_jan = data1["jan"].std()
print("Standar deviasi bulan Januari =", std_jan)

Rata-rata bulan Januari = 187.0
Variansi bulan Januari = 6584.444444444444
Standar deviasi bulan Januari = 81.14458974228931

In [ ]:
# P5 mengonversi array NumPy menjadi series Pandas

np_array = np.array([0, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)

new_np = pd.Series(np_array)
print("konversi Pandas series:")
print(new_np)

NumPy array:
[ 0 20 30 40 50]
konversi Pandas series:
0     0
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
# P6 https://numpy.org/doc/1.16/reference/generated/ numpy.random.RandomState.html

import pandas as pd
import numpy as np

#generate angka random
num_state = np.random.RandomState(100)
num_series = pd.Series(num_state.normal(10, 4, 20))
print(num_series)
print(num_state)

0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64
RandomState(MT19937)

In [ ]:
# P7.1 Load data dari file CSV
# Pastikan file penjualan.csv berada di folder yang sama dengan file Python

# import pandas as pd
# # Membaca file penjualan.csv
# df = pd.read_csv('penjualan.csv')

# # Menampilkan seluruh data
# df

In [ ]:
# P7.2 Load Data dari link

import pandas as pd

# Membaca file CSV langsung dari internet
df = pd.read_csv(
    'https://raw.githubusercontent.com/Alam-A99/Pandas_Latih/main/penjualan.csv'
)

# Menampilkan data
df

      nama  jan  feb  mar  apr
0     Andi  100  135   85   75
1     Budi  200  240  185  160
2  Chandra  300  315  285  190
3     Dudi  250  270  230  200
4      Eko  150  195  110  100
5    Fahri   95  130   75   45
6     Gina  125  175  110   70
7   Herman  130  155  100   85
8   Indara  320  374  300  270
9     Joni  200  220  175  155

In [ ]:
#P.12.2 Menampilkan baris indeks berlabel 0 dan kolom berlabel jan

df.loc[0,'jan']
df.iloc[0, 1]
df[['jan']][:1]

   jan
0  100

In [ ]:
#P.12.3 menampilkan baris 0-3, kolom 0(nama), 1(jan), 3 (maret)

df.iloc[0:3, [0, 1, 3]]

      nama  jan  mar
0     Andi  100   85
1     Budi  200  185
2  Chandra  300  285

In [ ]:
 # P12.4 Menampilkan semua baris pada kolom **nama** dan **apr**

df.loc[:, ['nama', 'apr']]
df.iloc[:, [0, 4]]
df[['nama', 'apr']]

      nama  apr
0     Andi   75
1     Budi  160
2  Chandra  190
3     Dudi  200
4      Eko  100
5    Fahri   45
6     Gina   70
7   Herman   85
8   Indara  270
9     Joni  155

In [ ]:
#P12.5 Menampilkan semua baris pada kolom nama sampai feb

df.loc[:, 'nama':'feb']
df.iloc[:, :3]
df[['nama', 'jan', 'feb']]

      nama  jan  feb
0     Andi  100  135
1     Budi  200  240
2  Chandra  300  315
3     Dudi  250  270
4      Eko  150  195
5    Fahri   95  130
6     Gina  125  175
7   Herman  130  155
8   Indara  320  374
9     Joni  200  220